/**
 * IndexNow notifier for marketing-page publishes.
 * Call when landing pages change — never for user image URLs.
 *
 * Set INDEXNOW_KEY via wrangler secret / .dev.vars once registered at indexnow.org.
 *
 * Inventory of indexable marketing URLs lives in marketing-urls.gen.ts
 * (regenerated by `npm run generate:pages`).
 */

import { MARKETING_URLS } from "./marketing-urls.gen";

export { MARKETING_URLS };

export async function notifyIndexNow(
  urls: string[],
  opts: { key: string; host?: string },
): Promise<void> {
  if (!opts.key || urls.length === 0) return;
  const host = opts.host ?? "dropimg.io";
  const body = {
    host,
    key: opts.key,
    keyLocation: `https://${host}/${opts.key}.txt`,
    urlList: urls,
  };
  try {
    await fetch("https://api.indexnow.org/indexnow", {
      method: "POST",
      headers: { "Content-Type": "application/json; charset=utf-8" },
      body: JSON.stringify(body),
    });
  } catch {
    // Best-effort; never fail a deploy/request on IndexNow
  }
}

/** Notify IndexNow for the full marketing URL inventory. */
export async function notifyMarketingIndexNow(opts: {
  key: string;
  host?: string;
}): Promise<void> {
  await notifyIndexNow([...MARKETING_URLS], opts);
}
