/** Auto-generated by scripts/generate-marketing-pages.ts — do not edit. */
export const MARKETING_URLS = [
  "https://dropimg.io/",
  "https://dropimg.io/es",
  "https://dropimg.io/pt-br",
  "https://dropimg.io/de",
  "https://dropimg.io/temporary-image-hosting",
  "https://dropimg.io/es/alojamiento-temporal-imagenes",
  "https://dropimg.io/pt-br/hospedagem-temporaria-de-imagens",
  "https://dropimg.io/de/temporaeres-bildhosting",
  "https://dropimg.io/paste-screenshot-online",
  "https://dropimg.io/es/pegar-captura-pantalla-online",
  "https://dropimg.io/pt-br/colar-captura-de-tela-online",
  "https://dropimg.io/de/screenshot-online-einfuegen",
  "https://dropimg.io/share-image-with-link",
  "https://dropimg.io/es/compartir-imagen-con-enlace",
  "https://dropimg.io/pt-br/compartilhar-imagem-com-link",
  "https://dropimg.io/de/bild-per-link-teilen"
] as const;
