/**
 * Build-time static marketing page generator.
 * Writes HTML for all locales + sitemap + IndexNow URL list.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { LOCALES, SITE_ORIGIN } from "../marketing/locales";
import { EXTENSION_URL } from "../marketing/extension";
import {
  INTENT_PAGE_IDS,
  allIntentUrls,
  intentLocales,
  intentPagePath,
  intentPageUrl,
} from "../marketing/intent-pages";
import {
  PAGE_IDS,
  allMarketingUrls,
  pageDir,
  pageUrl,
  type PageId,
} from "../marketing/pages";
import { allProUrls } from "../marketing/pro";
import {
  renderExtensionPage,
  renderIntentPage,
  renderPage,
} from "../marketing/render";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const LASTMOD = "2026-08-29";
const LEGAL_LASTMOD = "2026-08-29";

function htmlOutPath(pageId: PageId, locale: (typeof LOCALES)[number]): string {
  const dir = pageDir(pageId, locale);
  if (dir === ".") return join(root, "index.html");
  return join(root, dir, "index.html");
}

function writePage(pageId: PageId, locale: (typeof LOCALES)[number]) {
  const html = renderPage(pageId, locale);
  const out = htmlOutPath(pageId, locale);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html, "utf8");
  console.log(`  ${pageUrl(pageId, locale)} → ${out.replace(root + "/", "")}`);
}

function writeSitemap() {
  const marketing = allMarketingUrls();
  const legal = [
    `${SITE_ORIGIN}/privacy.html`,
    `${SITE_ORIGIN}/terms.html`,
    `${SITE_ORIGIN}/abuse`,
  ];
  const extension = [EXTENSION_URL];
  const intents = allIntentUrls();
  const pro = allProUrls();

  const urls = [
    ...marketing.map((loc) => {
      const pathOnly = loc.replace(SITE_ORIGIN, "") || "/";
      const isLocaleHome =
        pathOnly === "/" ||
        pathOnly === "/es" ||
        pathOnly === "/pt-br" ||
        pathOnly === "/de";
      return {
        loc,
        priority: isLocaleHome ? (pathOnly === "/" ? "1.0" : "0.9") : "0.8",
        changefreq: isLocaleHome ? "weekly" : "monthly",
      };
    }),
    ...extension.map((loc) => ({
      loc,
      priority: "0.7",
      changefreq: "monthly",
      lastmod: LASTMOD,
    })),
    ...pro.map((loc) => ({
      loc,
      priority: "0.85",
      changefreq: "weekly",
      lastmod: LASTMOD,
    })),
    ...intents.map((loc) => ({
      loc,
      priority: "0.75",
      changefreq: "monthly",
      lastmod: LASTMOD,
    })),
    ...legal.map((loc) => ({
      loc,
      priority: loc.includes("abuse") ? "0.4" : "0.3",
      changefreq: "yearly",
      lastmod: LEGAL_LASTMOD,
    })),
  ];

  // Dedupe by loc
  const seen = new Set<string>();
  const entries = urls.filter((u) => {
    if (seen.has(u.loc)) return false;
    seen.add(u.loc);
    return true;
  });

  const body = entries
    .map(
      (u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${"lastmod" in u && u.lastmod ? u.lastmod : LASTMOD}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`,
    )
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
  writeFileSync(join(root, "public/sitemap.xml"), xml, "utf8");
  console.log(`  sitemap → public/sitemap.xml (${entries.length} urls)`);
}

function writeMarketingUrlsModule() {
  const urls = [...allMarketingUrls(), EXTENSION_URL, ...allIntentUrls()];
  const src = `/** Auto-generated by scripts/generate-marketing-pages.ts — do not edit. */
export const MARKETING_URLS = ${JSON.stringify(urls, null, 2)} as const;
`;
  writeFileSync(join(root, "src/lib/marketing-urls.gen.ts"), src, "utf8");
  console.log(`  IndexNow inventory → src/lib/marketing-urls.gen.ts`);
}

function writeExtensionPage() {
  const html = renderExtensionPage();
  const out = join(root, "browser-extension/index.html");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html, "utf8");
  console.log(`  ${EXTENSION_URL} → browser-extension/index.html`);
}

function writeIntentPages() {
  for (const id of INTENT_PAGE_IDS) {
    for (const locale of intentLocales(id)) {
      const html = renderIntentPage(id, locale);
      const dir = intentPagePath(id, locale).replace(/^\//, "");
      const out = join(root, dir, "index.html");
      mkdirSync(dirname(out), { recursive: true });
      writeFileSync(out, html, "utf8");
      console.log(`  ${intentPageUrl(id, locale)} → ${dir}/index.html`);
    }
  }
}

console.log("Generating marketing pages…");
for (const pageId of PAGE_IDS) {
  for (const locale of LOCALES) {
    writePage(pageId, locale);
  }
}
writeExtensionPage();
writeIntentPages();
writeSitemap();
writeMarketingUrlsModule();
console.log("Done.");
