/**
 * Build-time static marketing page generator.
 * Writes HTML for all locales + sitemap + IndexNow URL list.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { LOCALES, SITE_ORIGIN } from "../marketing/locales";
import {
  PAGE_IDS,
  allMarketingUrls,
  pageDir,
  pageUrl,
  type PageId,
} from "../marketing/pages";
import { renderPage } from "../marketing/render";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const LASTMOD = "2026-08-23";

function htmlOutPath(pageId: PageId, locale: (typeof LOCALES)[number]): string {
  const dir = pageDir(pageId, locale);
  if (dir === ".") return join(root, "index.html");
  return join(root, dir, "index.html");
}

function writePage(pageId: PageId, locale: (typeof LOCALES)[number]) {
  const html = renderPage(pageId, locale);
  const out = htmlOutPath(pageId, locale);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, html, "utf8");
  console.log(`  ${pageUrl(pageId, locale)} → ${out.replace(root + "/", "")}`);
}

function writeSitemap() {
  const marketing = allMarketingUrls();
  const legal = [
    `${SITE_ORIGIN}/privacy.html`,
    `${SITE_ORIGIN}/terms.html`,
    `${SITE_ORIGIN}/abuse`,
  ];

  const urls = [
    ...marketing.map((loc) => {
      const pathOnly = loc.replace(SITE_ORIGIN, "") || "/";
      const isLocaleHome =
        pathOnly === "/" ||
        pathOnly === "/es" ||
        pathOnly === "/pt-br" ||
        pathOnly === "/de";
      return {
        loc,
        priority: isLocaleHome ? (pathOnly === "/" ? "1.0" : "0.9") : "0.8",
        changefreq: isLocaleHome ? "weekly" : "monthly",
      };
    }),
    ...legal.map((loc) => ({
      loc,
      priority: loc.includes("abuse") ? "0.4" : "0.3",
      changefreq: "yearly",
    })),
  ];

  // Dedupe by loc
  const seen = new Set<string>();
  const entries = urls.filter((u) => {
    if (seen.has(u.loc)) return false;
    seen.add(u.loc);
    return true;
  });

  const body = entries
    .map(
      (u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${LASTMOD}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`,
    )
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
  writeFileSync(join(root, "public/sitemap.xml"), xml, "utf8");
  console.log(`  sitemap → public/sitemap.xml (${entries.length} urls)`);
}

function writeMarketingUrlsModule() {
  const urls = allMarketingUrls();
  const src = `/** Auto-generated by scripts/generate-marketing-pages.ts — do not edit. */
export const MARKETING_URLS = ${JSON.stringify(urls, null, 2)} as const;
`;
  writeFileSync(join(root, "src/lib/marketing-urls.gen.ts"), src, "utf8");
  console.log(`  IndexNow inventory → src/lib/marketing-urls.gen.ts`);
}

console.log("Generating marketing pages…");
for (const pageId of PAGE_IDS) {
  for (const locale of LOCALES) {
    writePage(pageId, locale);
  }
}
writeSitemap();
writeMarketingUrlsModule();
console.log("Done.");
